# Informações do projeto
sonar.projectKey=SME-NovaSondagem-Worker
sonar.projectName=SME-NovaSondagem-Worker
sonar.projectVersion=1.0

# Caminho dos fontes
sonar.sources=.
sonar.sourceEncoding=UTF-8

# Exclusões
sonar.exclusions=**/bin/**,**/obj/**,**/Migrations/**,**/wwwroot/**

# Cobertura de testes (se houver)
sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml
sonar.cs.vstest.reportsPaths=**/*.trx

# Linguagem
sonar.language=cs