<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="MediatR" Version="14.0.0" />
    <PackageReference Include="Polly" Version="8.6.5" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Queries\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SME.NovaSondagem.Dados\SME.NovaSondagem.Dados.csproj" />
    <ProjectReference Include="..\SME.NovaSondagem.Infra\SME.NovaSondagem.Infra.csproj" />
  </ItemGroup>

</Project>
